version: '3'

services:

  Eureka:
    container_name: serviceregistry
    build: ./eurekaServer-master
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "eureka"
    environment:
      - eureka.client.serviceUrl.defaultZone = http://serviceregistry:8761/eureka/

  Gataway:
    container_name: gataway
    build: ./Cloud-getway-service
    ports:
      - "8089:8089"
    hostname: gataway
    environment:
      - eureka.client.serviceUrl.defaultZone = http://serviceregistry:8761/eureka/
    image: gateway
    depends_on:
      - Eureka

  Fournisseurs:
    container_name: fournisseurs
    build: ./ServiceFournisseur-main
    ports:
      - "8099:8099"
    hostname: fournisseurs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_1:3306/fournisseurs?createDatabaseIfNotExist=true&useUnicode=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - eureka.client.serviceUrl.defaultZone = http://serviceregistry:8761/eureka/
    image: "fournisseurs"
    depends_on:
      - docker-mysql_1
      - Eureka


  docker-mysql_1:
    container_name: mysql1
    image: mariadb:10.4.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"


  Panier:
    container_name: panier
    build: ./ServicePanier-master
    ports:
      - "8062:8062"
    hostname: panier
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_1:3306/servicepanier?createDatabaseIfNotExist=true&useUnicode=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - eureka.client.serviceUrl.defaultZone = http://serviceregistry:8761/eureka/
    image: "panier"
    depends_on:
      - docker-mysql_1
      - Eureka

  Commande:
    container_name: commande
    build: ./commandeService-master
    ports:
      - "8083:8083"
    hostname: commande
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_1:3306/serviceCommande?createDatabaseIfNotExist=true&useUnicode=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - eureka.client.serviceUrl.defaultZone = http://serviceregistry:8761/eureka/
    image: "commande"
    depends_on:
      - docker-mysql_1
      - Eureka


  react:
    build: ./FrontEnd-micro-master
    ports:
      - "3000:3000"

    image: "react"
    command: npm start


  userservicemongo:
    build: ./UserServiceMongo-master
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI = mongodb://mongo:27017/DevSpace
      - eureka.client.serviceUrl.defaultZone = http://serviceregistry:8761/eureka/
    command: npm start
    image: userservicemongo
    depends_on:
      - mongodb


  mongodb:
    image: mongo:4.0.3
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=DevSpace

      #Produit:
      # container_name: produit
      #build: .\commandeService-master
      #ports:
      # - "8092:8092"
      #environment:
      # - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka

      #image: "produit"
      #depends_on:
      # - Eureka






