version: "2.7"
services:
  
  commande:
 
    build: C:\Users\Skander\Desktop\ProjetMicroserviceAll\commandeService
    ports:
      - "8083:8083"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_2:3306/serviceCommande?autoReconnect=true&useSSL=false
     
    image: "commande"
    depends_on:
      - mysql_2
      - discovery

  servicepanier:

    build: C:\Users\Skander\Desktop\ProjetMicroserviceAll\ServicePanier
    ports:
      - "8062:8062"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_4:3306/servicepanier?autoReconnect=true&useSSL=false
     
    image: "servicepanier"
    depends_on:
      - mysql_4
      - discovery
 

 
    
 
  produit:

    build: C:\Users\Skander\Desktop\ProjetMicroserviceAll\serviceProduit2
    ports:
      - "8092:8092"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
   
    image: "produit"
    depends_on:
      - discovery
    

  
 
  facture:
 
    build: C:\Users\Skander\Desktop\ProjetMicroserviceAll\FactureMS
    ports:
      - "8084:8084"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
   
    image: "facture"
    depends_on:
      - discovery


  article:

    build: C:\Users\Skander\Desktop\ProjetMicroserviceAll\serviceArticle2
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
 
 
     
    image: "article"
    depends_on:
      - discovery
   
  fournisseur:

    build: C:\Users\Skander\Desktop\ProjetMicroserviceAll\ServiceFournisseur
    ports:
      - "8099:8099"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_3:3306/fournisseurs?autoReconnect=true&useSSL=false
     
    image: "fournisseur"
    depends_on:
      - mysql_3  
      - discovery
   

      
   
  
  
   
  mysql_2:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=serviceCommande
    ports:
      - 3311:3306
  mysql_3:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fournisseurs
    ports:
      - 3309:3306        
 
  mysql_4:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=servicepanier
    ports:
      - 3310:3306   
      
  
  apigateway:
    container_name: apigateway
    build: C:\Users\Skander\Desktop\ProjetMicroserviceAll\Cloud-getway-service
    ports:
      - "8089:8089"
    hostname: apigateway
    environment:
      ports:    
    image: "apigateway"  
    depends_on:
      -  discovery     
  
  
  userservicemongo: 
    build : C:\Users\Skander\Desktop\ProjetMicroserviceAll\UserServiceMongo
    ports:
      - "5000:5000"
    environment: 
     - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
    command: npm start
    volumes:
      - C:\Users\Skander\Desktop\ProjetMicroserviceAll\UserServiceMongo\app
      - C:\Users\Skander\Desktop\ProjetMicroserviceAll\UserServiceMongo\app\node_modules
    image : userservicemongo
    depends_on:
      -  discovery
 
 
 
  
  react: 
    build: C:\Users\Skander\Desktop\microservice\front\react
    ports : 
      - "3000:3000"
    
    image : "react"
    command: npm start
    volumes:
      - C:\Users\Skander\Desktop\microservice\front\react\
      - C:\Users\Skander\Desktop\microservice\front\react\node_modules
  
  
  discovery:
    build: C:\Users\Skander\Desktop\ProjetMicroserviceAll\eurekaServer
    ports:
      - 8761:8761
    image: eureka




#version: "3"
#services:
#  mysqldb:
#    image: mysql:5.7
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#      - eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
#    ports:
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#    volumes:
#      - db:/var/lib/mysql
#  app:
#    depends_on:
#      - mysqldb
#      - Eureka
#    build: C:\Users\Adam\Desktop\MicroService\MicroserviceProject
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update",
#        "eureka.client.serviceUrl.defaultZone" : "http://127.0.0.1:8761/eureka/"
#          }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true
#
#  fournisseur:
#    depends_on:
#      - mysqldb
#      - Eureka
#    build: C:\Users\Adam\Desktop\MicroService\ServiceFournisseur
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - "8099:8099"
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update",
#        "eureka.client.serviceUrl.defaultZone" : "http://127.0.0.1:8761/eureka/"
#          }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true
#  
#  Eureka:
#     build: C:\Users\Adam\Desktop\MicroService\EurekaMicroservice
#     image: eureka
#     ports:
#      - "8761:8761"
#  
#  
#volumes:
#  db:
#
#
